DROP TABLE STORE IF EXISTS;

CREATE TABLE STORE (
    ID INTEGER generated by default as identity (start with 1) not null,  
    NAME varchar(64) not null,
    TYPE varchar(64) not null,
    ADDRESS varchar(255) not null,
	CREATED timestamp,
	CONSTRAINT ID PRIMARY KEY (ID)
);

